Linaro/ledge-oe-manifest

conf/bblayers.conf
default.xml

meta-ledge got some directories re-arranged. Reflect these changes to the
manifest

meta-ledge: update to latest meta-ledge

---

README.md
conf/bblayers.conf
default.xml

Folow changes introduced on meta-ledge

manifest: update changes in meta-ledge

---

default.xml

Open62541 are an implementation of OPC UA
Change-Id: Iea96e9e867e6b9471e2d085ba75cd34aafb4037e

Add support of open62541

---

default.xml

This is no more available
Change-Id: I81e6f83193f38b62ea4b840b2b9649107039446a
Signed-off-by: vishal <vishal.bhoj@linaro.org>

remove meta-ltd osf repo

---

conf/bblayers.conf
default.xml

Include marvell espressobin support added on meta-ledge

layers: add support for meta-marvell

---

conf/bblayers.conf
conf/local.conf

conf: move BBMASK from bblayers to local config

---

default.xml

include meta-ledge support for stm32mp157c-dk2

---

conf/bblayers.conf
default.xml

Addition of several tool on ledge-gateway image.

Add selinux, python3 and run-C

---

default.xml

Switch to ARM GCC 8.2 toolchain
Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>

default.xml: update meta-rpb revision

---

conf/bblayers.conf
default.xml

Since we'll be using cloud-init on our ledge-iot platform add the
meta-layer that includes that

layers: add meta-openstack

---

conf/bblayers.conf
default.xml

add meta-secure-core for mokutil app

---

setup-environment-internal

nice print after adding environment

---

default.xml

u-boot: align device tree with kernel

---

default.xml

For stm32mp157c-dk2: add support of template for flashlayout

update: support several image build as same time

---

default.xml

default.xml: add dependant layer 96boards

---

conf/bblayers.conf

new bitbake errors on duplicated layers.

bblayers.conf: remove duplicates from config

---

README.md

update README.md with run wic image and qemu not about second boot

---

conf/multiconfig/README.txt
conf/multiconfig/launch_bitbake_multi_arm64.sh
conf/multiconfig/launch_bitbake_multi_armhf.sh
conf/multiconfig/qemuarm.conf
conf/multiconfig/qemuarm64.conf
conf/multiconfig/stm32mp157c-dk2.conf
conf/multiconfig/synquacer.conf
conf/multiconfig/ti-am572x.conf
setup-environment-internal

- README: readme to help to compile
- script to help for mc: launch_bitbake_multi_armhf.sh and
launch_bitbake_multi_arm64.sh
- configuration for each machine available
Change-Id: I3c9c25874348baa959088e0cdb52f2ef45fb993f

Multiconfig configuration

---

patches/0003-wic-filemap-If-FIGETBSZ-iotctl-fail-failback-to-os.s.patch

Change-Id: I6bd27f100117e3cefa66f59b4fa96545bf38ea03

WIC: backpart patch form master for FIGETBSZ iotctl fail

---

patches/0005-add-include-patch-wic-support.patch

wic: add upstream patch for --include-path

---

patches/0005-wic-Add-include-path-argument.patch

more clean cherry-pick of the patch.

fix 0005-wic-Add-include-path-argument.patch

---

default.xml

@apalos @cpriouzeau  in manifest we already have zeus branch. We can use it for branching and tagging and continue do development in master branch.

bind commits in meta ledge and link docs

---

setup-environment-internal

stm: fix reference to atf firmware

---

patches/0007-podman-compile-in-build-directory.patch

Change-Id: I896b7769402e6fe084c6165b6432f124bab0df35

add 0007-podman-compile-in-build-directory.patch to fix podman build
